import { Bike } from "./types";

export const IDR_TO_USD = 16000;

export const BIKES: Bike[] = [
  {
    id: "honda-scoopy",
    name: "Honda Scoopy",
    type: ["Popular", "Beginner", "Retro"],
    engineSize: 110,
    bestFor: ["City", "Photo"],
    hasABS: false,
    hasBigTrunk: false,
    hasPhoneHolder: true,
    hasUSB: true,
    pricePerDay: 85000,
    priceWeekly: 80000,
    priceMonthly: 45000,
    image: "https://images.unsplash.com/photo-1558981403-c5f91cbba527?auto=format&fit=crop&q=80&w=800",
    description: "Stylish retro scooter perfect for relaxed Bali rides, cafes and beach sunsets.",
    features: ["USB charger", "lightweight", "retro"]
  },
  {
    id: "yamaha-nmax",
    name: "Yamaha NMAX",
    type: ["Popular", "Maxi"],
    engineSize: 155,
    bestFor: ["City", "Long Trip", "Couple"],
    hasABS: true,
    hasBigTrunk: true,
    hasPhoneHolder: true,
    hasUSB: true,
    pricePerDay: 150000,
    priceWeekly: 135000,
    priceMonthly: 65000,
    image: "https://images.unsplash.com/photo-1558981403-c5f91cbba527?auto=format&fit=crop&q=80&w=800",
    description: "Premium scooter with powerful performance and maximum comfort for Bali adventures.",
    features: ["ABS", "Large trunk", "Keyless", "LED"]
  },
  {
    id: "honda-vario-125",
    name: "Honda Vario 125",
    type: "Budget",
    engineSize: 125,
    bestFor: ["City"],
    hasABS: false,
    hasBigTrunk: false,
    hasPhoneHolder: true,
    hasUSB: false,
    pricePerDay: 85000,
    priceWeekly: 80000,
    priceMonthly: 50000,
    image: "https://images.unsplash.com/photo-1558981403-c5f91cbba527?auto=format&fit=crop&q=80&w=800",
    description: "Stylish and easy-to-ride scooter, perfect for everyday Bali adventures.",
    features: ["Flat floor for bags", "agile"]
  },
  {
    id: "honda-vario-160",
    name: "Honda Vario 160",
    type: "Popular",
    engineSize: 160,
    bestFor: ["City"],
    hasABS: true,
    hasBigTrunk: false,
    hasPhoneHolder: true,
    hasUSB: true,
    pricePerDay: 90000,
    priceWeekly: 85000,
    priceMonthly: 55000,
    image: "https://images.unsplash.com/photo-1558981403-c5f91cbba527?auto=format&fit=crop&q=80&w=800",
    description: "Stylish and easy-to-ride scooter, perfect for everyday Bali adventures.",
    features: ["ABS", "Disc brakes", "high power"]
  },
  {
    id: "honda-pcx",
    name: "Honda PCX",
    type: ["Popular", "Maxi"],
    engineSize: 160,
    bestFor: ["City", "Long Trip", "Couple"],
    hasABS: true,
    hasBigTrunk: true,
    hasPhoneHolder: true,
    hasUSB: true,
    pricePerDay: 150000,
    priceWeekly: 135000,
    priceMonthly: 65000,
    image: "https://images.unsplash.com/photo-1558981403-c5f91cbba527?auto=format&fit=crop&q=80&w=800",
    description: "Premium scooter with smooth ride, spacious seat and maximum comfort for stylish Bali journeys.",
    features: ["ABS", "Large fuel tank", "premium comfort"]
  },
  {
    id: "yamaha-aerox",
    name: "Yamaha Aerox",
    type: "Popular",
    engineSize: 155,
    bestFor: ["City"],
    hasABS: true,
    hasBigTrunk: false,
    hasPhoneHolder: true,
    hasUSB: true,
    pricePerDay: 150000,
    priceWeekly: 135000,
    priceMonthly: 65000,
    image: "https://images.unsplash.com/photo-1558981403-c5f91cbba527?auto=format&fit=crop&q=80&w=800",
    description: "Sporty scooter with aggressive design and dynamic performance for energetic Bali rides.",
    features: ["ABS", "Sporty look", "wide tires"]
  },
  {
    id: "vespa-sprint",
    name: "Vespa Sprint",
    type: "Retro",
    engineSize: 150,
    bestFor: ["City", "Photo", "Couple"],
    hasABS: true,
    hasBigTrunk: false,
    hasPhoneHolder: true,
    hasUSB: true,
    pricePerDay: 250000,
    priceWeekly: 225000,
    priceMonthly: 140000,
    image: "https://images.unsplash.com/photo-1558981403-c5f91cbba527?auto=format&fit=crop&q=80&w=800",
    description: "Iconic Italian scooter perfect for stylish Bali rides and unforgettable Instagram photos.",
    features: ["ABS", "Steel body", "status", "Italian style"]
  },
  {
    id: "honda-adv",
    name: "Honda ADV",
    type: "Maxi",
    engineSize: 160,
    bestFor: ["Long Trip", "Mountains"],
    hasABS: true,
    hasBigTrunk: true,
    hasPhoneHolder: true,
    hasUSB: true,
    pricePerDay: 175000,
    priceWeekly: 155000,
    priceMonthly: 65000,
    image: "https://images.unsplash.com/photo-1558981403-c5f91cbba527?auto=format&fit=crop&q=80&w=800",
    description: "Adventure-style scooter built for exploring Bali with comfort, power and premium travel vibes.",
    features: ["ABS", "Crossover suspension", "smooth ride"]
  },
  {
    id: "yamaha-xmax",
    name: "Yamaha XMAX",
    type: "Maxi",
    engineSize: 250,
    bestFor: ["Long Trip", "Mountains", "Couple"],
    hasABS: true,
    hasBigTrunk: true,
    hasPhoneHolder: true,
    hasUSB: true,
    pricePerDay: 260000,
    priceWeekly: 240000,
    priceMonthly: 140000,
    image: "https://images.unsplash.com/photo-1558981403-c5f91cbba527?auto=format&fit=crop&q=80&w=800",
    description: "Premium maxi scooter with ultimate comfort, power and style for unforgettable Bali road trips.",
    features: ["ABS", "Fits 2 helmets", "Traction Control"]
  },
  {
    id: "yamaha-fazzio",
    name: "Yamaha Fazzio",
    type: ["Beginner", "Retro"],
    engineSize: 125,
    bestFor: ["City", "Photo"],
    hasABS: false,
    hasBigTrunk: false,
    hasPhoneHolder: true,
    hasUSB: false,
    pricePerDay: 85000,
    priceWeekly: 80000,
    priceMonthly: 50000,
    image: "https://images.unsplash.com/photo-1558981403-c5f91cbba527?auto=format&fit=crop&q=80&w=800",
    description: "Trendy and stylish scooter perfect for Bali cafes, beach sunsets and aesthetic island adventures.",
    features: ["Hybrid engine", "stylish design"]
  }
];
